FROM eclipse-temurin:17-jre-jammy

LABEL maintainer="inventoryservice.com"

COPY target/inventoryservice-0.0.1-SNAPSHOT.jar inventoryservice-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","inventoryservice-0.0.1-SNAPSHOT.jar"]
